Vagrant.configure(2) do |config|

  config.vm.provision "bash", type: "file" do |f|
    f.source = "~/.bash_profile"
    f.destination = ".bash_profile"
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo insecure >> ~/.curlrc
  SHELL

end
